name: 'Markdown -> Outline sync'
description: 'Sync markdown to getoutline.com pages'
branding:
  icon: 'grid'
  color: 'green'
inputs:
  files:
    description: 'the path to the files to sync'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
